name: Validate Manifest

on:
  pull_request:
    branches:
      - master
    paths:
      - 'manifests/**/*.installer.yaml'  # Trigger for changes in any installer.yaml files in the manifests directory

jobs:
  validation:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Identify Changed Installer Manifests
        run: |
          git fetch --depth=2
          $changedFiles = git diff --name-only HEAD^ HEAD | Where-Object { $_ -like 'manifests/**/*.installer.yaml' }
          foreach ($file in $changedFiles) {
            echo "Changed file: $file"
            echo "installer_manifest=$file" | Out-File -FilePath $env:GITHUB_ENV -Append
          }
        shell: pwsh

      - name: Run Validation Script on Changed Installer Manifests
        if: env.installer_manifest
        run: |
          $changedInstallerManifests = (Get-Content -Path $env:GITHUB_ENV | Select-String -Pattern "^installer_manifest=")
          foreach ($manifest in $changedInstallerManifests) {
            $manifestPath = $manifest -replace '^installer_manifest=', ''
            .\scripts\validation.ps1 -ApiKey ${{ secrets.VIRUSTOTAL_API_KEY }} -ManifestPath "$env:GITHUB_WORKSPACE/$manifestPath"
          }
        shell: pwsh
